server:
  port: 8000        # Gateway runs on this port

spring:
  application:
    name: gateway   # name registered in Consul

  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://user-service  # `lb://` tells the Gateway to use load balancing and service discovery.
          predicates:
            - Path=/api/v1/users/**       # Routes all requests with "/api/v1/users/" to User Service

        - id: contentservice
          uri: lb://contentservice
          predicates:
            - Path=/api/v1/content/**     # Routes all requests with "/api/v1/content/" to Content Service

        - id: progressservice
          uri: lb://progressservice
          predicates:
            - Path=/api/v1/progress/**    # Routes all requests with "/progress/" to Progress Service

        - id: gamificationservice
          uri: lb://gamificationservice
          predicates:
            - Path=/api/v1/trophies/**    # Routes all requests with "/trophies/" to Gamification Service
      discovery:
        locator:
          enabled: true  # Enables service discovery for routing
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
  config:
    import: "optional:consul:"  # imports config from Consul
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
