server:
  port: ${SERVER_PORT:8083}          # ProgressService will run on this port

spring:
  application:
    name: progressservice     # name registered in Consul
  rabbitmq: # RabbitMQ setup
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    consul:
      discovery:
        enabled: true
        prefer-ip-address: true
  config:
    import: "optional:consul:" # Imports optional configurations from Consul
  datasource:
    url: jdbc:postgresql://postgres:5432/mathplatform
    username: math
    password: math
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: progress_schema
    show-sql: true