server:
  port: 8083          # ProgressService will run on this port

spring:
  application:
    name: progress-service     # name registered in Consul
  cloud:
    consul:
      discovery:
        enabled: true
        prefer-ip-address: true
  config:
    import: "optional:consul:" # Imports config from Consul
  rabbitmq:                    # RabbitMQ setup
    host: localhost
    port: 5672
    username: guest
    password: guest