server:
  port: ${SERVER_PORT:8082}          # UserService will run on this port

spring:
  profiles:
    active: dev
  application:
    name: userservice     # name registered in Consul
  cloud:
    consul:
      discovery:
        enabled: true
        prefer-ip-address: true
  config:
    import: "optional:consul:" # Imports config from Consul