server:
  port: 8081          # ContentService will run on this port

spring:
  application:
    name: content-service     # name registered in Consul
  cloud:
    consul:
      discovery:
        enabled: true
        prefer-ip-address: true
  config:
    import: "optional:consul:" # Imports config from Consul
  rabbitmq:                    # RabbitMQ setup
    host: localhost
    port: 5672
    username: guest
    password: guest
