spring:
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1 # In-memory db for development
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true    # Enables H2 Console
  jpa:
    hibernate:
      ddl-auto: update # Updates schema automatically
    show-sql: true     # Show SQL queries in console
    database-platform: org.hibernate.dialect.H2Dialect