server:
  port: ${SERVER_PORT:8084}          # GamificationService will run on this port

spring:
  profiles:
    active: dev
  application:
    name: gamificationservice     # name registered in Consul
  rabbitmq: # RabbitMQ setup
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    consul:
      discovery:
        enabled: true
        prefer-ip-address: true
  config:
    import: "optional:consul:" # Imports config from Consul